spring.application.name=fridge-helper

notion.api-key=${NOTION_API_KEY:}
notion.database-id=${NOTION_DATABASE_ID:}
notion.base-url=${NOTION_BASE_URL:https://api.notion.com}
notion.version=${NOTION_VERSION:2026-03-11}
